apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cte-csi-sc
provisioner: cte.csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  key_manager_addr: 20.223.240.26
  k8_storage_group: isw-storage-group
  registration_token: nh4pCAEk8uKlnlqBwEDKDLDyLQWvTuGd2MqOCSf3w7J7hxVSuZVd5pzf9U3wInta # TO BE SET