apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: isw-gke-app.az.presales.dev
  namespace: default
spec:
  secretName: isw-gke-app.az.presales.dev-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: isw-gke-app.az.presales.dev
  dnsNames:
  - isw-gke-app.az.presales.dev